export const getAll = async (req: Request, res: Response) => {
  try {
    const estoques = [
    {
      id: 1,
      nome_produto: "Stainless Steel BBQ Grill Set",
      quantidade: 11,
      cue: 49.99,
      mpm: 2.49,
      preco: 49.99,
    },
    {
      id: 2,
      nome_produto: "Solar Power Bank",
      quantidade: 37,
      cue: 39.99,
      mpm: 4.99,
      preco: 2.99,
    },
    {
      id: 3,
      nome_produto: "Cherry Almond Protein Bar",
      quantidade: 81,
      cue: 1.99,
      mpm: 14.99,
      preco: 3.59,
    },
    {
      id: 4,
      nome_produto: "Self-Adhesive Wallpaper",
      quantidade: 57,
      cue: 34.99,
      mpm: 5.99,
      preco: 2.89,
    },
    {
      id: 5,
      nome_produto: "Leather Wallet",
      quantidade: 99,
      cue: 49.99,
      mpm: 4.49,
      preco: 2.99,
    },
    {
      id: 6,
      nome_produto: "Spinach Feta Wraps",
      quantidade: 15,
      cue: 4.29,
      mpm: 2.99,
      preco: 4.49,
    },
    {
      id: 7,
      nome_produto: "Smart Plug",
      quantidade: 14,
      cue: 19.99,
      mpm: 4.49,
      preco: 39.99,
    },
    {
      id: 8,
      nome_produto: "Slingback Sandals",
      quantidade: 80,
      cue: 29.99,
      mpm: 199.99,
      preco: 5.49,
    },
    {
      id: 9,
      nome_produto: "Pet Grooming Gloves",
      quantidade: 83,
      cue: 9.99,
      mpm: 149.99,
      preco: 4.99,
    },
    {
      id: 10,
      nome_produto: "Safety Pin Dispenser",
      quantidade: 92,
      cue: 5.99,
      mpm: 3.29,
      preco: 59.99,
    },
    {
      id: 11,
      nome_produto: "Children's Educational Workbook",
      quantidade: 59,
      cue: 12.99,
      mpm: 3.99,
      preco: 3.59,
    },
    {
      id: 12,
      nome_produto: "Electric Pressure Cooker",
      quantidade: 26,
      cue: 89.99,
      mpm: 34.99,
      preco: 8.99,
    },
    {
      id: 13,
      nome_produto: "Savory Quinoa Pudding",
      quantidade: 72,
      cue: 2.99,
      mpm: 49.99,
      preco: 14.99,
    },
    {
      id: 14,
      nome_produto: "Travel Makeup Organizer",
      quantidade: 65,
      cue: 25.99,
      mpm: 3.49,
      preco: 3.99,
    },
    {
      id: 15,
      nome_produto: "Cinnamon Sugar Mix",
      quantidade: 71,
      cue: 1.49,
      mpm: 5.49,
      preco: 39.99,
    },
    {
      id: 16,
      nome_produto: "Travel Luggage Scale",
      quantidade: 78,
      cue: 14.99,
      mpm: 6.99,
      preco: 3.49,
    },
    {
      id: 17,
      nome_produto: "Cheese Stuffed Jalapenos",
      quantidade: 44,
      cue: 5.99,
      mpm: 39.99,
      preco: 19.99,
    },
    {
      id: 18,
      nome_produto: "Set of Gardening Gloves with Claws",
      quantidade: 40,
      cue: 15.99,
      mpm: 15.99,
      preco: 3.49,
    },
    {
      id: 19,
      nome_produto: "Sooji (Semolina)",
      quantidade: 72,
      cue: 1.99,
      mpm: 2.49,
      preco: 34.99,
    },
    {
      id: 20,
      nome_produto: "Digital Drawing Tablet",
      quantidade: 16,
      cue: 79.99,
      mpm: 59.99,
      preco: 18.99,
    },
    {
      id: 21,
      nome_produto: "Vegetable Korma",
      quantidade: 86,
      cue: 6.49,
      mpm: 2.99,
      preco: 2.79,
    },
    {
      id: 22,
      nome_produto: "Chocolate Covered Pretzels",
      quantidade: 91,
      cue: 3.29,
      mpm: 2.49,
      preco: 4.89,
    },
    {
      id: 23,
      nome_produto: "Smart Thermostat",
      quantidade: 92,
      cue: 149.99,
      mpm: 29.99,
      preco: 14.99,
    },
    {
      id: 24,
      nome_produto: "Waterproof Rain Boots",
      quantidade: 13,
      cue: 69.99,
      mpm: 19.99,
      preco: 1.49,
    },
    {
      id: 25,
      nome_produto: "Vanilla Pudding Mix",
      quantidade: 35,
      cue: 1.29,
      mpm: 1.29,
      preco: 9.99,
    },
    {
      id: 26,
      nome_produto: "Mini Indoor Herb Garden Kit",
      quantidade: 52,
      cue: 24.99,
      mpm: 8.99,
      preco: 4.99,
    },
    {
      id: 27,
      nome_produto: "Energy Bites",
      quantidade: 69,
      cue: 3.99,
      mpm: 29.99,
      preco: 10.99,
    },
    {
      id: 28,
      nome_produto: "Beef Stew Meat",
      quantidade: 21,
      cue: 5.99,
      mpm: 24.99,
      preco: 199.99,
    },
    {
      id: 29,
      nome_produto: "Instant Read Meat Thermometer",
      quantidade: 68,
      cue: 24.99,
      mpm: 34.99,
      preco: 299.99,
    },
    {
      id: 30,
      nome_produto: "Peanut Butter Chocolate Clusters",
      quantidade: 19,
      cue: 2.99,
      mpm: 2.99,
      preco: 1.99,
    },
    {
      id: 31,
      nome_produto: "Smartphone Tripod with Bluetooth Remote",
      quantidade: 30,
      cue: 29.99,
      mpm: 4.49,
      preco: 39.99,
    },
    {
      id: 32,
      nome_produto: "Portable Hammock with Stand",
      quantidade: 71,
      cue: 69.99,
      mpm: 39.99,
      preco: 24.99,
    },
    {
      id: 33,
      nome_produto: "High-Low Hem Tee",
      quantidade: 53,
      cue: 22.99,
      mpm: 34.99,
      preco: 99.99,
    },
    {
      id: 34,
      nome_produto: "Sliced Bread",
      quantidade: 95,
      cue: 2.99,
      mpm: 3.99,
      preco: 1.99,
    },
    {
      id: 35,
      nome_produto: "Glass Tea Pot",
      quantidade: 38,
      cue: 34.99,
      mpm: 19.99,
      preco: 24.99,
    },
    {
      id: 36,
      nome_produto: "Telescope",
      quantidade: 48,
      cue: 159.99,
      mpm: 29.99,
      preco: 3.29,
    },
    {
      id: 37,
      nome_produto: "Sushi Rice",
      quantidade: 12,
      cue: 3.99,
      mpm: 18.99,
      preco: 29.99,
    },
    {
      id: 38,
      nome_produto: "Classic Minestrone Soup",
      quantidade: 54,
      cue: 2.99,
      mpm: 29.99,
      preco: 4.99,
    },
    {
      id: 39,
      nome_produto: "Kids' Art Easel",
      quantidade: 79,
      cue: 58.99,
      mpm: 29.99,
      preco: 7.99,
    },
    {
      id: 40,
      nome_produto: "Beef Stroganoff Meal Kit",
      quantidade: 44,
      cue: 12.99,
      mpm: 2.99,
      preco: 4.29,
    },
    {
      id: 41,
      nome_produto: "Cotton Pajama Set",
      quantidade: 55,
      cue: 49.99,
      mpm: 2.79,
      preco: 89.99,
    },
    {
      id: 42,
      nome_produto: "Smartphone Hand Grip",
      quantidade: 93,
      cue: 9.99,
      mpm: 5.49,
      preco: 3.99,
    },
    {
      id: 43,
      nome_produto: "Maple Almond Granola",
      quantidade: 59,
      cue: 5.49,
      mpm: 64.99,
      preco: 5.99,
    },
    {
      id: 44,
      nome_produto: "Smartphone Gimbal Stabilizer",
      quantidade: 10,
      cue: 89.99,
      mpm: 29.99,
      preco: 39.99,
    },
    {
      id: 45,
      nome_produto: "Kids' Science Experiment Kit",
      quantidade: 83,
      cue: 29.99,
      mpm: 6.99,
      preco: 14.99,
    },
    {
      id: 46,
      nome_produto: "Satin Slip Dress",
      quantidade: 89,
      cue: 59.99,
      mpm: 29.99,
      preco: 4.49,
    },
    {
      id: 47,
      nome_produto: "Lightweight Rain Jacket",
      quantidade: 71,
      cue: 79.99,
      mpm: 3.49,
      preco: 4.99,
    },
    {
      id: 48,
      nome_produto: "Savory Italian Herbs",
      quantidade: 20,
      cue: 2.99,
      mpm: 349.99,
      preco: 1.99,
    },
    {
      id: 49,
      nome_produto: "Set of Silicone Cooking Utensils",
      quantidade: 28,
      cue: 29.99,
      mpm: 5.99,
      preco: 24.99,
    },
    {
      id: 50,
      nome_produto: "Vegetable Fried Rice",
      quantidade: 41,
      cue: 4.99,
      mpm: 4.99,
      preco: 2.79,
    },
    {
      id: 51,
      nome_produto: "Fitness Jump Box",
      quantidade: 49,
      cue: 69.99,
      mpm: 2.49,
      preco: 3.49,
    },
    {
      id: 52,
      nome_produto: "Portable Solar Camp Shower",
      quantidade: 2,
      cue: 29.99,
      mpm: 2.99,
      preco: 22.99,
    },
    {
      id: 53,
      nome_produto: "Salsa",
      quantidade: 31,
      cue: 3.49,
      mpm: 39.99,
      preco: 4.99,
    },
    {
      id: 54,
      nome_produto: "Dill Pickle Chips",
      quantidade: 36,
      cue: 2.29,
      mpm: 109.99,
      preco: 19.99,
    },
    {
      id: 55,
      nome_produto: "Nature Explorer Lens Kit",
      quantidade: 53,
      cue: 19.99,
      mpm: 49.99,
      preco: 49.99,
    },
    {
      id: 56,
      nome_produto: "Pet Camera with Treat Dispenser",
      quantidade: 90,
      cue: 149.99,
      mpm: 24.99,
      preco: 59.99,
    },
    {
      id: 57,
      nome_produto: "Portable Phone Charger",
      quantidade: 56,
      cue: 29.99,
      mpm: 1.99,
      preco: 5.29,
    },
    {
      id: 58,
      nome_produto: "Wireless Range Extender",
      quantidade: 34,
      cue: 49.99,
      mpm: 39.99,
      preco: 199.99,
    },
    {
      id: 59,
      nome_produto: "Wrist Support Brace",
      quantidade: 65,
      cue: 19.99,
      mpm: 89.99,
      preco: 45,
    },
    {
      id: 60,
      nome_produto: "Silicone Ice Cube Tray",
      quantidade: 91,
      cue: 10.99,
      mpm: 44.99,
      preco: 34.99,
    },
    {
      id: 61,
      nome_produto: "Spicy Beef Taco Mix",
      quantidade: 92,
      cue: 1.99,
      mpm: 4.49,
      preco: 3.49,
    },
    {
      id: 62,
      nome_produto: "Watercolor Set",
      quantidade: 4,
      cue: 19.99,
      mpm: 12.99,
      preco: 7.99,
    },
    {
      id: 63,
      nome_produto: "Ergonomic Mouse Pad with Wrist Support",
      quantidade: 80,
      cue: 14.99,
      mpm: 2.99,
      preco: 3.79,
    },
    {
      id: 64,
      nome_produto: "Blender Bottle",
      quantidade: 55,
      cue: 12.99,
      mpm: 32.99,
      preco: 24.99,
    },
    {
      id: 65,
      nome_produto: "Spiced Pumpkin Soup",
      quantidade: 16,
      cue: 3.99,
      mpm: 4.29,
      preco: 12.99,
    },
    {
      id: 66,
      nome_produto: "Brussels Sprouts",
      quantidade: 54,
      cue: 3.49,
      mpm: 4.29,
      preco: 5.49,
    },
    {
      id: 67,
      nome_produto: "Multi-Function Meat Tenderizer",
      quantidade: 73,
      cue: 19.99,
      mpm: 4.99,
      preco: 4.89,
    },
    {
      id: 68,
      nome_produto: "Luxury Bath Robe",
      quantidade: 64,
      cue: 49.99,
      mpm: 12.99,
      preco: 1.99,
    },
    {
      id: 69,
      nome_produto: "Lentil Pasta",
      quantidade: 37,
      cue: 4.99,
      mpm: 349.99,
      preco: 19.99,
    },
    {
      id: 70,
      nome_produto: "Tropical Fruit Bowl",
      quantidade: 6,
      cue: 4.99,
      mpm: 2.99,
      preco: 34.99,
    },
    {
      id: 71,
      nome_produto: "Printed Maxi Skirt",
      quantidade: 25,
      cue: 39.99,
      mpm: 129.99,
      preco: 2.99,
    },
    {
      id: 72,
      nome_produto: "Slim Fit Chinos",
      quantidade: 33,
      cue: 54.99,
      mpm: 29.99,
      preco: 4.99,
    },
    {
      id: 73,
      nome_produto: "Electronic Drum Kit",
      quantidade: 72,
      cue: 359.99,
      mpm: 29.99,
      preco: 109.99,
    },
    {
      id: 74,
      nome_produto: "Fruit and Nut Bars",
      quantidade: 76,
      cue: 1.99,
      mpm: 1.99,
      preco: 19.99,
    },
    {
      id: 75,
      nome_produto: "Creamy Tomato Basil Soup",
      quantidade: 21,
      cue: 3.29,
      mpm: 3.29,
      preco: 5.99,
    },
    {
      id: 76,
      nome_produto: "Kale Chips",
      quantidade: 7,
      cue: 3.99,
      mpm: 4.19,
      preco: 3.49,
    },
    {
      id: 77,
      nome_produto: "Herb Seasoned Croutons",
      quantidade: 41,
      cue: 2.99,
      mpm: 6.99,
      preco: 34.99,
    },
    {
      id: 78,
      nome_produto: "Gluten-Free Biscuits",
      quantidade: 56,
      cue: 3.79,
      mpm: 24.99,
      preco: 3.29,
    },
    {
      id: 79,
      nome_produto: "LED Canopy Lights",
      quantidade: 26,
      cue: 29.99,
      mpm: 59.99,
      preco: 2.99,
    },
    {
      id: 80,
      nome_produto: "Multi-Layer Food Steamer",
      quantidade: 61,
      cue: 39.99,
      mpm: 29.99,
      preco: 59.99,
    },
    {
      id: 81,
      nome_produto: "Spicy Thai Coconut Soup",
      quantidade: 47,
      cue: 3.99,
      mpm: 39.99,
      preco: 22.99,
    },
    {
      id: 82,
      nome_produto: "Baby Monitor",
      quantidade: 85,
      cue: 79.99,
      mpm: 12.99,
      preco: 199.99,
    },
    {
      id: 83,
      nome_produto: "Zesty Garlic Marinade",
      quantidade: 11,
      cue: 4.49,
      mpm: 1.99,
      preco: 58.99,
    },
    {
      id: 84,
      nome_produto: "Portable Leaf Blower",
      quantidade: 74,
      cue: 149.99,
      mpm: 3.29,
      preco: 4.99,
    },
    {
      id: 85,
      nome_produto: "LED Canopy Lights",
      quantidade: 45,
      cue: 29.99,
      mpm: 1.49,
      preco: 39.99,
    },
    {
      id: 86,
      nome_produto: "Granola Cereal",
      quantidade: 5,
      cue: 4.49,
      mpm: 24.99,
      preco: 4.49,
    },
    {
      id: 87,
      nome_produto: "Oven Mitts",
      quantidade: 64,
      cue: 15.99,
      mpm: 49.99,
      preco: 4.99,
    },
    {
      id: 88,
      nome_produto: "Dog Training Clicker",
      quantidade: 14,
      cue: 5.99,
      mpm: 34.99,
      preco: 25.99,
    },
    {
      id: 89,
      nome_produto: "Cat Tree with Scratching Posts",
      quantidade: 71,
      cue: 79.99,
      mpm: 19.99,
      preco: 34.99,
    },
    {
      id: 90,
      nome_produto: "Pet Grooming Gloves",
      quantidade: 30,
      cue: 9.99,
      mpm: 2.49,
      preco: 29.99,
    },
    {
      id: 91,
      nome_produto: "Zucchini Noodle Pasta",
      quantidade: 98,
      cue: 3.99,
      mpm: 24.99,
      preco: 59.99,
    },
    {
      id: 92,
      nome_produto: "Granola Bars",
      quantidade: 37,
      cue: 4.99,
      mpm: 19.99,
      preco: 15.99,
    },
    {
      id: 93,
      nome_produto: "USB Desk Fan",
      quantidade: 89,
      cue: 14.99,
      mpm: 19.99,
      preco: 3.49,
    },
    {
      id: 94,
      nome_produto: "Baked Mac and Cheese",
      quantidade: 16,
      cue: 5.99,
      mpm: 3.49,
      preco: 9.99,
    },
    {
      id: 95,
      nome_produto: "Mini Fondue Set",
      quantidade: 95,
      cue: 34.99,
      mpm: 6.49,
      preco: 29.99,
    },
    {
      id: 96,
      nome_produto: "Peanut Butter Granola",
      quantidade: 25,
      cue: 4.99,
      mpm: 39.99,
      preco: 3.49,
    },
    {
      id: 97,
      nome_produto: "Wooden Blocks",
      quantidade: 86,
      cue: 24.99,
      mpm: 5.99,
      preco: 39.99,
    },
    {
      id: 98,
      nome_produto: "Kids' Crafting Station",
      quantidade: 36,
      cue: 49.99,
      mpm: 4.99,
      preco: 2.99,
    },
    {
      id: 99,
      nome_produto: "Cinnamon Sugar Tortilla Chips",
      quantidade: 36,
      cue: 3.29,
      mpm: 29.99,
      preco: 22.99,
    },
    {
      id: 100,
      nome_produto: "Children's Science Experiment Lab Kit",
      quantidade: 60,
      cue: 29.99,
      mpm: 3.49,
      preco: 49.99,
    },
  ];
    res.status(200).json(estoques);
  } catch (error) {
    res.status(500).json({ message: "Erro ao buscar estoques", error });
  }
};

export const getById = async (req: Request, res: Response) => {
  try {
    const { id } = req.query;
    const estoques = [
    {
      id: 1,
      nome_produto: "Stainless Steel BBQ Grill Set",
      quantidade: 11,
      cue: 49.99,
      mpm: 2.49,
      preco: 49.99,
    },
    {
      id: 2,
      nome_produto: "Solar Power Bank",
      quantidade: 37,
      cue: 39.99,
      mpm: 4.99,
      preco: 2.99,
    },
    {
      id: 3,
      nome_produto: "Cherry Almond Protein Bar",
      quantidade: 81,
      cue: 1.99,
      mpm: 14.99,
      preco: 3.59,
    },
    {
      id: 4,
      nome_produto: "Self-Adhesive Wallpaper",
      quantidade: 57,
      cue: 34.99,
      mpm: 5.99,
      preco: 2.89,
    },
    {
      id: 5,
      nome_produto: "Leather Wallet",
      quantidade: 99,
      cue: 49.99,
      mpm: 4.49,
      preco: 2.99,
    },
    {
      id: 6,
      nome_produto: "Spinach Feta Wraps",
      quantidade: 15,
      cue: 4.29,
      mpm: 2.99,
      preco: 4.49,
    },
    {
      id: 7,
      nome_produto: "Smart Plug",
      quantidade: 14,
      cue: 19.99,
      mpm: 4.49,
      preco: 39.99,
    },
    {
      id: 8,
      nome_produto: "Slingback Sandals",
      quantidade: 80,
      cue: 29.99,
      mpm: 199.99,
      preco: 5.49,
    },
    {
      id: 9,
      nome_produto: "Pet Grooming Gloves",
      quantidade: 83,
      cue: 9.99,
      mpm: 149.99,
      preco: 4.99,
    },
    {
      id: 10,
      nome_produto: "Safety Pin Dispenser",
      quantidade: 92,
      cue: 5.99,
      mpm: 3.29,
      preco: 59.99,
    },
    {
      id: 11,
      nome_produto: "Children's Educational Workbook",
      quantidade: 59,
      cue: 12.99,
      mpm: 3.99,
      preco: 3.59,
    },
    {
      id: 12,
      nome_produto: "Electric Pressure Cooker",
      quantidade: 26,
      cue: 89.99,
      mpm: 34.99,
      preco: 8.99,
    },
    {
      id: 13,
      nome_produto: "Savory Quinoa Pudding",
      quantidade: 72,
      cue: 2.99,
      mpm: 49.99,
      preco: 14.99,
    },
    {
      id: 14,
      nome_produto: "Travel Makeup Organizer",
      quantidade: 65,
      cue: 25.99,
      mpm: 3.49,
      preco: 3.99,
    },
    {
      id: 15,
      nome_produto: "Cinnamon Sugar Mix",
      quantidade: 71,
      cue: 1.49,
      mpm: 5.49,
      preco: 39.99,
    },
    {
      id: 16,
      nome_produto: "Travel Luggage Scale",
      quantidade: 78,
      cue: 14.99,
      mpm: 6.99,
      preco: 3.49,
    },
    {
      id: 17,
      nome_produto: "Cheese Stuffed Jalapenos",
      quantidade: 44,
      cue: 5.99,
      mpm: 39.99,
      preco: 19.99,
    },
    {
      id: 18,
      nome_produto: "Set of Gardening Gloves with Claws",
      quantidade: 40,
      cue: 15.99,
      mpm: 15.99,
      preco: 3.49,
    },
    {
      id: 19,
      nome_produto: "Sooji (Semolina)",
      quantidade: 72,
      cue: 1.99,
      mpm: 2.49,
      preco: 34.99,
    },
    {
      id: 20,
      nome_produto: "Digital Drawing Tablet",
      quantidade: 16,
      cue: 79.99,
      mpm: 59.99,
      preco: 18.99,
    },
    {
      id: 21,
      nome_produto: "Vegetable Korma",
      quantidade: 86,
      cue: 6.49,
      mpm: 2.99,
      preco: 2.79,
    },
    {
      id: 22,
      nome_produto: "Chocolate Covered Pretzels",
      quantidade: 91,
      cue: 3.29,
      mpm: 2.49,
      preco: 4.89,
    },
    {
      id: 23,
      nome_produto: "Smart Thermostat",
      quantidade: 92,
      cue: 149.99,
      mpm: 29.99,
      preco: 14.99,
    },
    {
      id: 24,
      nome_produto: "Waterproof Rain Boots",
      quantidade: 13,
      cue: 69.99,
      mpm: 19.99,
      preco: 1.49,
    },
    {
      id: 25,
      nome_produto: "Vanilla Pudding Mix",
      quantidade: 35,
      cue: 1.29,
      mpm: 1.29,
      preco: 9.99,
    },
    {
      id: 26,
      nome_produto: "Mini Indoor Herb Garden Kit",
      quantidade: 52,
      cue: 24.99,
      mpm: 8.99,
      preco: 4.99,
    },
    {
      id: 27,
      nome_produto: "Energy Bites",
      quantidade: 69,
      cue: 3.99,
      mpm: 29.99,
      preco: 10.99,
    },
    {
      id: 28,
      nome_produto: "Beef Stew Meat",
      quantidade: 21,
      cue: 5.99,
      mpm: 24.99,
      preco: 199.99,
    },
    {
      id: 29,
      nome_produto: "Instant Read Meat Thermometer",
      quantidade: 68,
      cue: 24.99,
      mpm: 34.99,
      preco: 299.99,
    },
    {
      id: 30,
      nome_produto: "Peanut Butter Chocolate Clusters",
      quantidade: 19,
      cue: 2.99,
      mpm: 2.99,
      preco: 1.99,
    },
    {
      id: 31,
      nome_produto: "Smartphone Tripod with Bluetooth Remote",
      quantidade: 30,
      cue: 29.99,
      mpm: 4.49,
      preco: 39.99,
    },
    {
      id: 32,
      nome_produto: "Portable Hammock with Stand",
      quantidade: 71,
      cue: 69.99,
      mpm: 39.99,
      preco: 24.99,
    },
    {
      id: 33,
      nome_produto: "High-Low Hem Tee",
      quantidade: 53,
      cue: 22.99,
      mpm: 34.99,
      preco: 99.99,
    },
    {
      id: 34,
      nome_produto: "Sliced Bread",
      quantidade: 95,
      cue: 2.99,
      mpm: 3.99,
      preco: 1.99,
    },
    {
      id: 35,
      nome_produto: "Glass Tea Pot",
      quantidade: 38,
      cue: 34.99,
      mpm: 19.99,
      preco: 24.99,
    },
    {
      id: 36,
      nome_produto: "Telescope",
      quantidade: 48,
      cue: 159.99,
      mpm: 29.99,
      preco: 3.29,
    },
    {
      id: 37,
      nome_produto: "Sushi Rice",
      quantidade: 12,
      cue: 3.99,
      mpm: 18.99,
      preco: 29.99,
    },
    {
      id: 38,
      nome_produto: "Classic Minestrone Soup",
      quantidade: 54,
      cue: 2.99,
      mpm: 29.99,
      preco: 4.99,
    },
    {
      id: 39,
      nome_produto: "Kids' Art Easel",
      quantidade: 79,
      cue: 58.99,
      mpm: 29.99,
      preco: 7.99,
    },
    {
      id: 40,
      nome_produto: "Beef Stroganoff Meal Kit",
      quantidade: 44,
      cue: 12.99,
      mpm: 2.99,
      preco: 4.29,
    },
    {
      id: 41,
      nome_produto: "Cotton Pajama Set",
      quantidade: 55,
      cue: 49.99,
      mpm: 2.79,
      preco: 89.99,
    },
    {
      id: 42,
      nome_produto: "Smartphone Hand Grip",
      quantidade: 93,
      cue: 9.99,
      mpm: 5.49,
      preco: 3.99,
    },
    {
      id: 43,
      nome_produto: "Maple Almond Granola",
      quantidade: 59,
      cue: 5.49,
      mpm: 64.99,
      preco: 5.99,
    },
    {
      id: 44,
      nome_produto: "Smartphone Gimbal Stabilizer",
      quantidade: 10,
      cue: 89.99,
      mpm: 29.99,
      preco: 39.99,
    },
    {
      id: 45,
      nome_produto: "Kids' Science Experiment Kit",
      quantidade: 83,
      cue: 29.99,
      mpm: 6.99,
      preco: 14.99,
    },
    {
      id: 46,
      nome_produto: "Satin Slip Dress",
      quantidade: 89,
      cue: 59.99,
      mpm: 29.99,
      preco: 4.49,
    },
    {
      id: 47,
      nome_produto: "Lightweight Rain Jacket",
      quantidade: 71,
      cue: 79.99,
      mpm: 3.49,
      preco: 4.99,
    },
    {
      id: 48,
      nome_produto: "Savory Italian Herbs",
      quantidade: 20,
      cue: 2.99,
      mpm: 349.99,
      preco: 1.99,
    },
    {
      id: 49,
      nome_produto: "Set of Silicone Cooking Utensils",
      quantidade: 28,
      cue: 29.99,
      mpm: 5.99,
      preco: 24.99,
    },
    {
      id: 50,
      nome_produto: "Vegetable Fried Rice",
      quantidade: 41,
      cue: 4.99,
      mpm: 4.99,
      preco: 2.79,
    },
    {
      id: 51,
      nome_produto: "Fitness Jump Box",
      quantidade: 49,
      cue: 69.99,
      mpm: 2.49,
      preco: 3.49,
    },
    {
      id: 52,
      nome_produto: "Portable Solar Camp Shower",
      quantidade: 2,
      cue: 29.99,
      mpm: 2.99,
      preco: 22.99,
    },
    {
      id: 53,
      nome_produto: "Salsa",
      quantidade: 31,
      cue: 3.49,
      mpm: 39.99,
      preco: 4.99,
    },
    {
      id: 54,
      nome_produto: "Dill Pickle Chips",
      quantidade: 36,
      cue: 2.29,
      mpm: 109.99,
      preco: 19.99,
    },
    {
      id: 55,
      nome_produto: "Nature Explorer Lens Kit",
      quantidade: 53,
      cue: 19.99,
      mpm: 49.99,
      preco: 49.99,
    },
    {
      id: 56,
      nome_produto: "Pet Camera with Treat Dispenser",
      quantidade: 90,
      cue: 149.99,
      mpm: 24.99,
      preco: 59.99,
    },
    {
      id: 57,
      nome_produto: "Portable Phone Charger",
      quantidade: 56,
      cue: 29.99,
      mpm: 1.99,
      preco: 5.29,
    },
    {
      id: 58,
      nome_produto: "Wireless Range Extender",
      quantidade: 34,
      cue: 49.99,
      mpm: 39.99,
      preco: 199.99,
    },
    {
      id: 59,
      nome_produto: "Wrist Support Brace",
      quantidade: 65,
      cue: 19.99,
      mpm: 89.99,
      preco: 45,
    },
    {
      id: 60,
      nome_produto: "Silicone Ice Cube Tray",
      quantidade: 91,
      cue: 10.99,
      mpm: 44.99,
      preco: 34.99,
    },
    {
      id: 61,
      nome_produto: "Spicy Beef Taco Mix",
      quantidade: 92,
      cue: 1.99,
      mpm: 4.49,
      preco: 3.49,
    },
    {
      id: 62,
      nome_produto: "Watercolor Set",
      quantidade: 4,
      cue: 19.99,
      mpm: 12.99,
      preco: 7.99,
    },
    {
      id: 63,
      nome_produto: "Ergonomic Mouse Pad with Wrist Support",
      quantidade: 80,
      cue: 14.99,
      mpm: 2.99,
      preco: 3.79,
    },
    {
      id: 64,
      nome_produto: "Blender Bottle",
      quantidade: 55,
      cue: 12.99,
      mpm: 32.99,
      preco: 24.99,
    },
    {
      id: 65,
      nome_produto: "Spiced Pumpkin Soup",
      quantidade: 16,
      cue: 3.99,
      mpm: 4.29,
      preco: 12.99,
    },
    {
      id: 66,
      nome_produto: "Brussels Sprouts",
      quantidade: 54,
      cue: 3.49,
      mpm: 4.29,
      preco: 5.49,
    },
    {
      id: 67,
      nome_produto: "Multi-Function Meat Tenderizer",
      quantidade: 73,
      cue: 19.99,
      mpm: 4.99,
      preco: 4.89,
    },
    {
      id: 68,
      nome_produto: "Luxury Bath Robe",
      quantidade: 64,
      cue: 49.99,
      mpm: 12.99,
      preco: 1.99,
    },
    {
      id: 69,
      nome_produto: "Lentil Pasta",
      quantidade: 37,
      cue: 4.99,
      mpm: 349.99,
      preco: 19.99,
    },
    {
      id: 70,
      nome_produto: "Tropical Fruit Bowl",
      quantidade: 6,
      cue: 4.99,
      mpm: 2.99,
      preco: 34.99,
    },
    {
      id: 71,
      nome_produto: "Printed Maxi Skirt",
      quantidade: 25,
      cue: 39.99,
      mpm: 129.99,
      preco: 2.99,
    },
    {
      id: 72,
      nome_produto: "Slim Fit Chinos",
      quantidade: 33,
      cue: 54.99,
      mpm: 29.99,
      preco: 4.99,
    },
    {
      id: 73,
      nome_produto: "Electronic Drum Kit",
      quantidade: 72,
      cue: 359.99,
      mpm: 29.99,
      preco: 109.99,
    },
    {
      id: 74,
      nome_produto: "Fruit and Nut Bars",
      quantidade: 76,
      cue: 1.99,
      mpm: 1.99,
      preco: 19.99,
    },
    {
      id: 75,
      nome_produto: "Creamy Tomato Basil Soup",
      quantidade: 21,
      cue: 3.29,
      mpm: 3.29,
      preco: 5.99,
    },
    {
      id: 76,
      nome_produto: "Kale Chips",
      quantidade: 7,
      cue: 3.99,
      mpm: 4.19,
      preco: 3.49,
    },
    {
      id: 77,
      nome_produto: "Herb Seasoned Croutons",
      quantidade: 41,
      cue: 2.99,
      mpm: 6.99,
      preco: 34.99,
    },
    {
      id: 78,
      nome_produto: "Gluten-Free Biscuits",
      quantidade: 56,
      cue: 3.79,
      mpm: 24.99,
      preco: 3.29,
    },
    {
      id: 79,
      nome_produto: "LED Canopy Lights",
      quantidade: 26,
      cue: 29.99,
      mpm: 59.99,
      preco: 2.99,
    },
    {
      id: 80,
      nome_produto: "Multi-Layer Food Steamer",
      quantidade: 61,
      cue: 39.99,
      mpm: 29.99,
      preco: 59.99,
    },
    {
      id: 81,
      nome_produto: "Spicy Thai Coconut Soup",
      quantidade: 47,
      cue: 3.99,
      mpm: 39.99,
      preco: 22.99,
    },
    {
      id: 82,
      nome_produto: "Baby Monitor",
      quantidade: 85,
      cue: 79.99,
      mpm: 12.99,
      preco: 199.99,
    },
    {
      id: 83,
      nome_produto: "Zesty Garlic Marinade",
      quantidade: 11,
      cue: 4.49,
      mpm: 1.99,
      preco: 58.99,
    },
    {
      id: 84,
      nome_produto: "Portable Leaf Blower",
      quantidade: 74,
      cue: 149.99,
      mpm: 3.29,
      preco: 4.99,
    },
    {
      id: 85,
      nome_produto: "LED Canopy Lights",
      quantidade: 45,
      cue: 29.99,
      mpm: 1.49,
      preco: 39.99,
    },
    {
      id: 86,
      nome_produto: "Granola Cereal",
      quantidade: 5,
      cue: 4.49,
      mpm: 24.99,
      preco: 4.49,
    },
    {
      id: 87,
      nome_produto: "Oven Mitts",
      quantidade: 64,
      cue: 15.99,
      mpm: 49.99,
      preco: 4.99,
    },
    {
      id: 88,
      nome_produto: "Dog Training Clicker",
      quantidade: 14,
      cue: 5.99,
      mpm: 34.99,
      preco: 25.99,
    },
    {
      id: 89,
      nome_produto: "Cat Tree with Scratching Posts",
      quantidade: 71,
      cue: 79.99,
      mpm: 19.99,
      preco: 34.99,
    },
    {
      id: 90,
      nome_produto: "Pet Grooming Gloves",
      quantidade: 30,
      cue: 9.99,
      mpm: 2.49,
      preco: 29.99,
    },
    {
      id: 91,
      nome_produto: "Zucchini Noodle Pasta",
      quantidade: 98,
      cue: 3.99,
      mpm: 24.99,
      preco: 59.99,
    },
    {
      id: 92,
      nome_produto: "Granola Bars",
      quantidade: 37,
      cue: 4.99,
      mpm: 19.99,
      preco: 15.99,
    },
    {
      id: 93,
      nome_produto: "USB Desk Fan",
      quantidade: 89,
      cue: 14.99,
      mpm: 19.99,
      preco: 3.49,
    },
    {
      id: 94,
      nome_produto: "Baked Mac and Cheese",
      quantidade: 16,
      cue: 5.99,
      mpm: 3.49,
      preco: 9.99,
    },
    {
      id: 95,
      nome_produto: "Mini Fondue Set",
      quantidade: 95,
      cue: 34.99,
      mpm: 6.49,
      preco: 29.99,
    },
    {
      id: 96,
      nome_produto: "Peanut Butter Granola",
      quantidade: 25,
      cue: 4.99,
      mpm: 39.99,
      preco: 3.49,
    },
    {
      id: 97,
      nome_produto: "Wooden Blocks",
      quantidade: 86,
      cue: 24.99,
      mpm: 5.99,
      preco: 39.99,
    },
    {
      id: 98,
      nome_produto: "Kids' Crafting Station",
      quantidade: 36,
      cue: 49.99,
      mpm: 4.99,
      preco: 2.99,
    },
    {
      id: 99,
      nome_produto: "Cinnamon Sugar Tortilla Chips",
      quantidade: 36,
      cue: 3.29,
      mpm: 29.99,
      preco: 22.99,
    },
    {
      id: 100,
      nome_produto: "Children's Science Experiment Lab Kit",
      quantidade: 60,
      cue: 29.99,
      mpm: 3.49,
      preco: 49.99,
    },
  ];
    const estoque = estoques.filter((e) => e.id === parseInt(id));
    if (!estoque) {
      return res.status(404).json({ message: "Estoque não encontrado" });
    }
    res.status(200).json(estoque);
  } catch (error) {
    res.status(500).json({ message: "Erro ao buscar estoque", error });
  }
};

// export const create = async (req: Request, res: Response) => {
//   try {
//     const newEstoque = new Estoque(req.body);
//     const savedEstoque = await newEstoque.save();
//     res.status(201).json(savedEstoque);
//   } catch (error) {
//     res.status(500).json({ message: "Erro ao criar estoque", error });
//   }
// };

// export const update = async (req: Request, res: Response) => {
//   try {
//     const { id } = req.params;
//     const updatedEstoque = await Estoque.findByIdAndUpdate(id, req.body, { new: true });
//     if (!updatedEstoque) {
//       return res.status(404).json({ message: "Estoque não encontrado" });
//     }
//     res.status(200).json(updatedEstoque);
//     } catch (error) {
//     res.status(500).json({ message: "Erro ao atualizar estoque", error });
//   }
// };

// export const delete = async (req: Request, res: Response) => {
//   try {
//     const { id } = req.params;
//     const deletedEstoque = await Estoque.findByIdAndDelete(id);
//     if (!deletedEstoque) {
//       return res.status(404).json({ message: "Estoque não encontrado" });
//     }
//     res.status(200).json({ message: "Estoque deletado com sucesso" });
//   } catch (error) {
//     res.status(500).json({ message: "Erro ao deletar estoque", error });
//   }
// };